### ISSUE TITLE
Help with installing

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/module-superhero-blog#8]
Hi,

This is great. However some things in the "how to install" is missing when I install this module on an existing EXP setup filled with other content. Just minor text-things to edit to make that guide perfect!

These are your bullet points, with my comments under each:

* In the admin console, create a site and give it a name.  
 Make it support this new module!
* Create folders called Authors, Categories and Posts.  
Cool (under that new site)
* Create a Category and an Author content in their respective folders.  
Cool
* Create a Post content in the Posts folder and add the Category and Author content.  
Cool
* When the above steps are done, create a page template and add the 70-30 Layout.  
It should support "Site" and use the correct page template controller ("Page"). Also, the layout is just called "Two column".
* Add the "Header" and "Posts list" parts to the left side of the layout.  
There is no part called "Header" anymore, do you mean "Featured"?
* Add the following parts to the right side of the layout: Search form, Recent posts, Recent comments, Archives, Categories and Tags.  
It's "Monthly archive" and "Tag cloud" now.
* Make this page template support the Site content type.  
Move this up? This must be done before being able to drag things in
* Create another page template called "Post show". Add the "Post single" part in the left instead of the "Posts list". Add the same parts from the previous step to the right column.  
Use "Page" controller. Also, should I add the layout part again? I guess so, just doesn't say so anywhere.
* Make the Post show template support the Post content type.   
Move up  a bit? Must be done right after you name the template.

**Comment by Michael-Lazell** [comment]
Hi Bobby,
Feel free to update that page with your suggestions if you like. I wrote that a long time ago, before the DemoImport was added, so it's probably not really needed now.
